# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Alsaif Analytics
description: "Alsaif Analytics is an analytics company that is on a mission to be our clients’ long-term partner in success, leveraging the power of data and other fields expertise to empower SMBs across the GCC region to reach their most ambitious goals. This portfolio showcases our data analytics capabilities using various analytics and machine learning tools."
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.alsaifanalytics.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Analytics <span style="color:#f58506"> Portfolio </span>
location: "United Arab Emirates/Kuwait"
resume_url: /docs/Fawaz Al-Saif CV JAN 2023.docx.docx
avatar_image: /img/alsaif-analytics-linkedin-profile-photo.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/company/alsaifanalytics/" # Add your linkedln handle
github: "https://github.com/AlsaifAnalytics"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

